name: Cactus CI Github Workflow

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      max-parallel: 1024
      matrix:
        os: [ubuntu-20.04]
        node-version: [v12.13.0, v14.15.1, v16.3.0]
        experimental: [false]

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v2.3.4

    - run: ./tools/ci.sh

  build-containers:
    runs-on: ubuntu-20.04
    continue-on-error: true
    
    steps:

    - uses: actions/checkout@v2.3.4
      name: Check out code

    - name: ghcr.io/hyperledger/cactus-dev-container-vscode
      run: DOCKER_BUILDKIT=1 docker build ./.devcontainer/ -f ./.devcontainer/Dockerfile

    - name: ghcr.io/hyperledger/cactus-example-supply-chain-app
      run: DOCKER_BUILDKIT=1 docker build . -f ./examples/supply-chain-app/Dockerfile

    - name: ghcr.io/hyperledger/cactus-example-carbon-accounting
      run: DOCKER_BUILDKIT=1 docker build . -f ./examples/carbon-accounting/Dockerfile

    - name: ghcr.io/hyperledger/cactus-cmd-api-server
      run: DOCKER_BUILDKIT=1 docker build . -f ./packages/cactus-cmd-api-server/Dockerfile

    - name: ghcr.io/hyperledger/cactus-cmd-api-server
      run: DOCKER_BUILDKIT=1 docker build ./packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/ -f ./packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/Dockerfile

    - name: ghcr.io/hyperledger/cactus-connector-corda-server
      run: DOCKER_BUILDKIT=1 docker build ./packages/cactus-plugin-ledger-connector-corda/src/main-server/ -f ./packages/cactus-plugin-ledger-connector-corda/src/main-server/Dockerfile

    - name: ghcr.io/hyperledger/cactus-connector-fabric
      run: DOCKER_BUILDKIT=1 docker build ./packages/cactus-plugin-ledger-connector-fabric/ -f ./packages/cactus-plugin-ledger-connector-fabric/Dockerfile

    - name: ghcr.io/hyperledger/cactus-connector-besu
      run: DOCKER_BUILDKIT=1 docker build ../packages/cactus-plugin-ledger-connector-besu/ -f ./packages/cactus-plugin-ledger-connector-besu/Dockerfile

    - name: ghcr.io/hyperledger/cactus-besu-all-in-one
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/besu-all-in-one/ -f ./tools/docker/besu-all-in-one/Dockerfile

    - name: ghcr.io/hyperledger/cactus-corda-all-in-one
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/corda-all-in-one/ -f ./tools/docker/corda-all-in-one/Dockerfile

    - name: ghcr.io/hyperledger/cactus-fabric2-all-in-one
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/fabric-all-in-one/ -f ./tools/docker/fabric-all-in-one/Dockerfile_v2.x

    - name: ghcr.io/hyperledger/cactus-fabric-all-in-one
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/fabric-all-in-one/ -f ./tools/docker/fabric-all-in-one/Dockerfile_v1.4.x

    - name: ghcr.io/hyperledger/cactus-quorum-all-in-one
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/quorum-all-in-one/ -f ./tools/docker/quorum-all-in-one/Dockerfile

    - name: ghcr.io/hyperledger/cactus-rust-compiler
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/rust-compiler/ -f ./tools/docker/rust-compiler/Dockerfile

    - name: ghcr.io/hyperledger/cactus-rust-compiler
      run: DOCKER_BUILDKIT=1 docker build ./tools/docker/test-npm-registry/ -f ./tools/docker/test-npm-registry/Dockerfile

    - name: ghcr.io/hyperledger/cactus-whitepaper
      run: DOCKER_BUILDKIT=1 docker build ./whitepaper/ -f ./whitepaper/Dockerfile
      